# Generated by Django 3.2.7 on 2021-09-14 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phoneNo', models.BigIntegerField(null=True)),
                ('passcode', models.TextField(null=True)),
                ('is_shop', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_wallet', to='datacontrol.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'CASH'), ('virtualwallet', 'Virtual Wallet'), ('crypto', 'Crypto Wallet')], max_length=30, null=True)),
                ('category', models.CharField(choices=[('orderpayment', 'ORDER PAYMENT'), ('transfer', 'MONEY TRANSFER')], max_length=30, null=True)),
                ('payment_id', models.TextField(default='', null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=30, null=True)),
                ('transaction_time', models.DateTimeField(null=True)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transaction_logs', to='datacontrol.baseuser')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transaction_logs', to='datacontrol.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('college_name', models.TextField(null=True)),
                ('department', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('roll_no', models.TextField(null=True)),
                ('email_id', models.TextField(default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='datacontrol.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('type', models.CharField(choices=[('canteen', 'CANTEEN'), ('stationary', 'STATIONARY SHOP'), ('printing', 'PRINTING SHOP')], default='canteen', max_length=30, null=True)),
                ('longitude_coordinate', models.FloatField(default=0.0, null=True)),
                ('latitude_coordinate', models.FloatField(default=0.0, null=True)),
                ('picture', models.TextField(default='', null=True)),
                ('operating_days', models.TextField(default='[]', null=True)),
                ('open_at', models.TextField(default='[]', null=True)),
                ('close_at', models.TextField(default='[]', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to='datacontrol.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('picture', models.TextField(null=True)),
                ('is_available', models.BooleanField(default=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='datacontrol.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('is_preorder', models.BooleanField(default=False, null=True)),
                ('preorder_scheduled_time', models.DateTimeField(null=True)),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=30, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_logs', to='datacontrol.shopprofile')),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_transaction_log', to='datacontrol.transactionlog')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celo_encrypted_mnemonic', models.TextField(null=True)),
                ('celo_address', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallet', to='datacontrol.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('borrowed_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('returned_on', models.DateTimeField(null=True)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_borrow_logs', to='datacontrol.baseuser')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_borrow_logs', to='datacontrol.baseuser')),
            ],
        ),
    ]
