# Generated by Django 3.2.7 on 2021-09-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0002_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phoneNo',
            field=models.FloatField(null=True),
        ),
    ]
