# Generated by Django 3.2.7 on 2021-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0003_alter_baseuser_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='open_at',
            field=models.TimeField(null=True),
        ),
    ]
