# Generated by Django 3.2.7 on 2021-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0004_auto_20210915_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='phoneNo',
            new_name='phone_no',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email_id',
            field=models.TextField(default='op', null=True),
        ),
    ]
