# Generated by Django 3.2.7 on 2021-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0005_auto_20210915_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='transaction_log',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='transaction_log_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email_id',
            field=models.TextField(default='', null=True),
        ),
    ]
