# Generated by Django 3.2.7 on 2021-09-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0006_auto_20210915_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
