# Generated by Django 3.2.7 on 2021-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0007_orderlog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='picture',
            field=models.FileField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
