# Generated by Django 3.2.6 on 2021-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0009_otpdirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdirectory',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpdirectory',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
