# Generated by Django 3.2.6 on 2021-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0010_auto_20210916_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='celo_address',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='celo_encrypted_mnemonic',
            field=models.TextField(editable=False, null=True),
        ),
    ]
