# Generated by Django 3.2.6 on 2021-09-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0012_auto_20210917_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'CASH'), ('virtualwallet', 'Virtual Wallet'), ('online', 'Online'), ('crypto', 'Crypto Wallet')], max_length=30, null=True),
        ),
    ]
