# Generated by Django 3.2.6 on 2021-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacontrol', '0013_alter_transactionlog_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='celo_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='celo_encrypted_mnemonic',
            field=models.TextField(null=True),
        ),
    ]
